#!/bin/bash
# ------------------------------------------------------------------------------
# OraDBA - Oracle Database Infrastructur and Security, 5630 Muri, Switzerland
# ------------------------------------------------------------------------------
# Name.......: 00_init_environment
# Author.....: Stefan Oehrli (oes) stefan.oehrli@oradba.ch
# Editor.....: Stefan Oehrli
# Date.......: 2025.12.15
# Version....: v4.0.0
# Purpose....: File for setting the instance-specific environment. 
#              The setup scripts are based on the OUD Base environment. 
#              If OUD Base is not used, you may have to adapt this file 
#              and set the specific parameter in section "default 
#              environment variables"
# Notes......: --
# Reference..: https://github.com/oehrlis/oudbase
# License....: Apache License Version 2.0, January 2004 as shown
#              at http://www.apache.org/licenses/
# ------------------------------------------------------------------------------
# Modified...:
# see git revision history with git log for more information on changes
# ------------------------------------------------------------------------------
# - default environment variables ---------------------------------------
# The default environment variables are already set correctly by OUD Base 
# and commented out at this point. It is important that the appropriate 
# environment is set. If OUD Base is not used, the following variables 
# must be set explicitly.
# ------------------------------------------------------------------------------
#export ORACLE_BASE="/opt/oracle"
#export ORACLE_HOME="${ORACLE_BASE}/product/oud12.2.1.3.0"
#export OUD_INSTANCE=ouddd
#export OUD_INSTANCE_ADMIN=${ORACLE_BASE}/admin/${OUD_INSTANCE}
#export OUD_INSTANCE_HOME="${ORACLE_BASE}/instances/${OUD_INSTANCE}"
#export PWD_FILE=${OUD_INSTANCE_ADMIN}/etc/${OUD_INSTANCE}_pwd.txt
#export PORT_ADMIN=4444
#export PORT=1389
#export PORT_SSL=1636
#export PORT_REP=8989
#export PORT_REP=8989
export PORT_REST_ADMIN=${PORT_REST_ADMIN:-"8444"}
export PORT_REST_HTTP=${PORT_REST_HTTP:-"1080"}
export PORT_REST_HTTPS=${PORT_REST_HTTPS:-"1081"}
# - End of default environment variables ---------------------------------------

# - Customization --------------------------------------------------------------
# - Miscellaneous Customizations
# <CUSTOM>

# - Instance information
export DIRMAN="cn=Directory Manager"
export REPMAN=admin
export BASEDN=${BASEDN:-"dc=trivadislabs,dc=com"}
export BASEDN_STRING=$(echo $BASEDN|sed 's/\(dc\|o\|ou\)=//g; s/,/_/g;')
export DEFAULT_PASSWORD=$ADMIN_PASSWORD         # default password for ldap users (none admin users)
export DEFAULT_ADMIN_PASSWORD=$ADMIN_PASSWORD   # default password for ldap admin users

export GROUP_OU="Groups"                        # group OU below base DN eg ou=groups,dc=postgasse,dc=org
export USER_OU="People"                         # user OU below base DN eg ou=people,dc=postgasse,dc=org
# - INTERNAL Suffix
export LOCAL_OU="ou=local"

# Create a list of all suffix based on variables with _SUFFIX
ALL_SUFFIX=""                        # initial values of ALL_SUFFIX
for i in $(env|cut -d= -f1|grep '_SUFFIX$'); do
    # check if environment variable is not empty and value not yet part of ALL_SUFFIX
    if [ -n "${!i}" ] && [[ $ALL_SUFFIX != *"${!i}"* ]]; then
        ALL_SUFFIX+="${!i} "
    fi
done

# - Certificates and password
export KEYSTOREFILE=${OUD_INSTANCE_HOME}/OUD/config/keystore
export KEYSTOREPIN=${OUD_INSTANCE_HOME}/OUD/config/keystore.pin
#export NICKNAME="NICKNAME"
#export PIN="PIN"

# AD Configuration
# - AD integration information
export AD_PDC_HOST="ad.trivadislabs.com"                                        # set the host name of your primary domain controller (PDC)
export AD_PDC_PORT=389                                                          # set the LDAP port for your PDC
export AD_PDC_USER="cn=oracle,cn=Users,dc=trivadislabs,dc=com"                  # set the MS AD account used by OUD to access AD
export AD_PDC_PASSWORD='LAB01schulung'                                          # set the password for the MS AD account
export AD_PDC_PASSWORD_FILE="${OUD_INSTANCE_ADMIN}/etc/ad_pwd_file.txt"         # set the password file for the MS AD account

# EUS Configuration
export EUS_USER_NAME="eusadmin"
export EUS_USER_DN="cn=${EUS_USER_NAME},cn=oraclecontext"
export COMMON_FILES=${OUD_INSTANCE_ADMIN}
export EUSADMIN_USERS_PWD_FILE=${COMMON_FILES}/etc/${EUS_USER_NAME}_pwd.txt
export EUSADMIN_USERS_DN_FILE=${COMMON_FILES}/etc/${EUS_USER_NAME}_dn.txt
echo ${EUS_USER_DN} >${EUSADMIN_USERS_DN_FILE}
export TRUSTED_CERT_FILE=${COMMON_FILES}/etc/oud_trusted_cert.txt

# Password files
export DEFAULT_USERS_PWD_FILE=${OUD_INSTANCE_ADMIN}/etc/${OUD_INSTANCE}_default_user_pwd.txt

# - Hosts
export DEFAULT_HOST=$(hostname 2>/dev/null ||cat /etc/hostname ||echo $HOSTNAME)   # Hostname
export HOST=${HOST:-$DEFAULT_HOST}
export HOST1=${HOST1:-$DEFAULT_HOST}
export HOST2=${HOST2:-$DEFAULT_HOST}
export HOST3=${HOST3:-$DEFAULT_HOST}
# - End of customization -------------------------------------------------------
