name: 🐛 Bug Report
description: Report a bug or unexpected behavior in oudbase
title: "[Bug]: "
labels: ["bug"]
assignees: []
body:
  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: Describe the bug and what you expected to happen
      placeholder: What's wrong and what should happen instead?
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component is affected?
      options:
        - oudenv.sh
        - TNS tools
        - OUD scripts
        - Templates
        - Other
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this issue?
      placeholder: |
        1. Run command '...'
        2. See error
      value: |
        1. 
        2. 
    validations:
      required: true

  - type: textarea
    id: error-output
    attributes:
      label: Error Output
      description: Paste any error messages or logs
      placeholder: Error messages or logs...
      render: shell
    validations:
      required: false

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Basic environment information
      placeholder: |
        - OS: Oracle Linux 8
        - OUD Version: 12.2.1.4.0
        - oudbase Version: v3.4.5
      value: |
        - OS: 
        - OUD Version: 
        - oudbase Version: 
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other relevant information (config snippets, workarounds, etc.)
      placeholder: Optional additional details...
    validations:
      required: false
