name: 📋 Task
description: Track work items, improvements, or refactoring tasks
title: "[Task]: "
labels: ["task"]
assignees: []
body:
  - type: textarea
    id: task-description
    attributes:
      label: Task Description
      description: What needs to be done and why?
      placeholder: Describe the task and its purpose...
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component will this affect?
      options:
        - oudenv.sh
        - TNS tools
        - OUD scripts
        - Templates
        - Tests
        - Documentation
        - Other
    validations:
      required: true

  - type: textarea
    id: implementation
    attributes:
      label: Implementation Details
      description: Brief plan of what needs to be done
      placeholder: |
        - Step 1
        - Step 2
        - Files to modify: ...
    validations:
      required: false

  - type: textarea
    id: additional-notes
    attributes:
      label: Additional Notes
      description: Any dependencies, risks, or other relevant information
      placeholder: Dependencies, blockers, or other context...
    validations:
      required: false
